[tool.poetry]
name = "rouquin"
version = "0.1.0"
description = ""
authors = ["Anouar Aïssaoui <tobia@crossbone.cc>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
